# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13CrQcCKrwHQhlQvAM-ZzdvA4BJYQwnEa
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from mnist_dataset import MNIST
from model import LeNet5

def train(model, trn_loader, device, criterion, optimizer):
    model.train()
    total_loss = 0.0
    correct = 0
    for data, target in trn_loader:
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * data.size(0)
        pred = output.argmax(dim=1, keepdim=True)
        correct += pred.eq(target.view_as(pred)).sum().item()
    trn_loss = total_loss / len(trn_loader.dataset)
    acc = correct / len(trn_loader.dataset)
    return trn_loss, acc

def test(model, tst_loader, device, criterion):
    model.eval()
    total_loss = 0.0
    correct = 0
    with torch.no_grad():
        for data, target in tst_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            total_loss += criterion(output, target).item() * data.size(0)
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()
    tst_loss = total_loss / len(tst_loader.dataset)
    acc = correct / len(tst_loader.dataset)
    return tst_loss, acc

def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # 데이터셋 및 데이터로더 생성
    train_dataset = MNIST(data_file="train.tar")
    test_dataset = MNIST(data_file="test.tar")
    train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

    # 모델, 손실 함수 및 optimizer 생성
    model = LeNet5().to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

    # 학습 및 테스트 실행
    for epoch in range(1, 3):  # 예시로 10 에폭까지만 실행
        trn_loss, trn_acc = train(model, train_loader, device, criterion, optimizer)
        tst_loss, tst_acc = test(model, test_loader, device, criterion)
        print(f"Epoch {epoch}:")
        print(f"Train Loss: {trn_loss:.4f}, Accuracy: {trn_acc:.4f}")
        print(f"Test Loss: {tst_loss:.4f}, Accuracy: {tst_acc:.4f}")

if __name__ == '__main__':
    main()
